version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: webpack
    versions:
    - 5.23.0
    - 5.24.0
    - 5.24.1
    - 5.24.2
    - 5.24.3
    - 5.24.4
    - 5.25.1
    - 5.26.0
    - 5.26.2
    - 5.26.3
    - 5.27.1
    - 5.27.2
    - 5.28.0
    - 5.30.0
    - 5.31.0
    - 5.31.2
    - 5.32.0
    - 5.33.2
    - 5.34.0
    - 5.35.0
    - 5.35.1
    - 5.36.0
  - dependency-name: css-loader
    versions:
    - 5.1.0
    - 5.1.1
    - 5.1.2
    - 5.1.3
    - 5.2.0
    - 5.2.1
    - 5.2.4
  - dependency-name: sass
    versions:
    - 1.32.11
    - 1.32.8
  - dependency-name: "@babel/core"
    versions:
    - 7.12.17
    - 7.13.1
    - 7.13.10
    - 7.13.13
    - 7.13.14
    - 7.13.15
    - 7.13.16
    - 7.13.8
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.17
    - 7.13.0
    - 7.13.10
    - 7.13.12
    - 7.13.15
    - 7.13.5
    - 7.13.8
    - 7.13.9
  - dependency-name: mini-css-extract-plugin
    versions:
    - 1.3.7
    - 1.3.8
    - 1.3.9
    - 1.4.0
    - 1.4.1
  - dependency-name: copy-webpack-plugin
    versions:
    - 7.0.0
    - 8.0.0
    - 8.1.0
  - dependency-name: "@bamdadsabbagh/stylelint-config"
    versions:
    - 1.3.0
  - dependency-name: "@bamdadsabbagh/eslint-config"
    versions:
    - 1.8.0
    - 1.8.2
    - 1.9.1
  - dependency-name: postcss-loader
    versions:
    - 5.0.0
    - 5.1.0
    - 5.2.0
  - dependency-name: html-webpack-plugin
    versions:
    - 5.0.0
    - 5.2.0
    - 5.3.0
    - 5.3.1
  - dependency-name: "@babel/plugin-proposal-class-properties"
    versions:
    - 7.13.0
  - dependency-name: webpack-cli
    versions:
    - 4.4.0
    - 4.5.0
  - dependency-name: sass-loader
    versions:
    - 11.0.0
    - 11.0.1
